seed: xxx   #seed：用于设置随机数生成器的种子。在深度学习训练中，随机数的使用很常见，比如初始化模型参数、划分数据集等。设置固定的种子可以保证实验的可重复性，即每次运行代码时，随机数的生成序列都是相同的
#分布式训练配置
dist_config:
  dist_backend: "nccl"  #dist_backend：指定分布式训练的后端通信协议
  dist_url: "tcp://localhost:54321"  #用于指定分布式训练中节点之间通信的地址和端口，这里设置为 tcp://localhost:54321，表示在本地的 54321 端口进行通信。如果是多机分布式训练，需要根据实际情况修改为相应的 IP 地址和端口。
  world_size: 1  #表示参与分布式训练的节点总数，这里设置为 1，说明是单机训练。
path:
  ckpt_path: "./output/ckpt/DailyTalk"   #ckpt_path：指定模型检查点（checkpoint）的保存路径。在训练过程中，会定期保存模型的参数，以便在需要时可以恢复训练或进行推理。
  log_path: "./output/log/DailyTalk"    #指定训练日志的保存路径。训练日志可以记录训练过程中的各种信息，如损失值、学习率等，方便后续分析训练过程。
  result_path: "./output/result/DailyTalk"  #指定训练结果的保存路径，可能包括合成的语音样本等。
optimizer:
  batch_size: 16  #每次训练时输入模型的样本数量。较大的批量大小可以提高训练的稳定性和效率，但也会增加内存的使用。
  betas: [0.9, 0.98]  #这是 Adam 优化器中用于计算梯度一阶矩估计和二阶矩估计的指数衰减率，通常取值为 [0.9, 0.98]。第一个值控制一阶矩估计的衰减率，第二个值控制二阶矩估计的衰减率。
  eps: 0.000000001  #一个很小的数值，用于避免在计算中出现除以零的情况
  weight_decay: 0.0  #权重衰减系数，用于防止模型过拟合。通过在损失函数中添加权重的 L2 正则化项，使得模型的权重不会过大。这里设置为 0.0，表示不使用权重衰减。
  grad_clip_thresh: 1.0  #梯度裁剪的阈值。在训练过程中，梯度可能会变得非常大，导致训练不稳定。梯度裁剪可以将梯度的范数限制在一个固定的阈值内，避免梯度爆炸。
  grad_acc_step: 1    #梯度累积的步数。当显存有限时，可以通过梯度累积来模拟较大的批量大小。梯度累积会在多个小批量上计算梯度，然后在达到指定的步数后再更新模型参数。这里设置为 1，表示不进行梯度累积。
  warm_up_step: 4000   #学习率预热的步数 4000 个 step（batch）。在训练开始时，使用较小的学习率可以帮助模型更稳定地收敛。学习率预热会在一定的步数内逐渐增加学习率，直到达到预设的初始学习率。
  anneal_steps: [300000, 400000, 500000]  #学习率衰减的步数列表。在训练过程中，随着训练的进行，学习率需要逐渐减小，以帮助模型更好地收敛。这里设置了三个衰减点，分别是 300000、400000 和 500000 步。
  anneal_rate: 0.3    #学习率衰减的比率。当达到 anneal_steps 中的某个步数时，学习率会乘以该比率进行衰减。

loss:
  dur_loss: "mse"  #指定持续时间损失函数的类型，这里使用 "mse"（均方误差）。在语音合成等任务中，持续时间的预测是一个重要的任务，均方误差可以衡量预测的持续时间与真实持续时间之间的差异。
  #lambda_ph_dur、lambda_word_dur、lambda_sent_dur：分别是音素级、单词级和句子级持续时间损失的权重系数。这些系数用于平衡不同级别持续时间损失对总损失的贡献。
  lambda_ph_dur: 1.0
  lambda_word_dur: 1.0
  lambda_sent_dur: 1.0
#每个batch算作一步
step:
  total_step: 900000  #训练的总步数。模型会在达到这个步数后停止训练。
  log_step: 100   #每隔多少步记录一次训练日志，方便监控训练过程。
  synth_step: 2000  #每隔多少步进行一次语音合成，用于检查模型的合成效果。
  val_step: 2000   #每隔多少步进行一次验证，评估模型在验证集上的性能。
  save_step: 2000   #每隔多少步保存一次模型的检查点，以便在需要时可以恢复训练。 #25000
  var_start_steps: 10000  #可能是指在训练初期某个阶段不启用方差（韵律）相关模块（如 Variance Adaptor），在 50,000 步后开始引入相关预测和调整。
#持续时间二值化配置
duration:
  binarization_start_steps: 6000  #持续时间二值化开始的步数。
  binarization_loss_enable_steps: 18000   #持续时间二值化损失开始启用的步数。在达到这个步数后，会在损失函数中加入持续时间二值化的损失项。
  binarization_loss_warmup_steps: 10000   #持续时间二值化损失的预热步数。在启用持续时间二值化损失后，会在一定的步数内逐渐增加该损失项的权重，避免对模型的训练造成过大的冲击。
